import { createHmac, timingSafeEqual } from 'node:crypto'
import { Money, exponentOf, type CurrencyCode } from '@fineduc/money'
import type { PaymentMethod, PaymentStatus } from '@fineduc/domain'
import { getJson, postJson, type FetchLike, type HttpPolicy } from '../../http.js'
import {
  ProviderError,
  type InitiatePaymentRequest,
  type InitiatePaymentResult,
  type NormalizedPaymentEvent,
  type PaymentProvider,
  type ProviderPaymentStatus,
  type RefundResult,
  type WebhookVerification,
} from '../port.js'

/**
 * Chariow — a hosted checkout for African mobile money (Orange Money, Wave,
 * MTN, Moov…) that also takes card.
 *
 * Chariow charges the price of a PRODUCT configured in the merchant's own
 * Chariow shop — there is no field for an arbitrary amount, only a
 * `discount_code` to reduce a product's fixed price. That makes it a fit for
 * Fineduc's OWN subscription billing, where a plan's price is fixed and known
 * in advance, and a poor fit for a parent's fee payment, where the amount is
 * whatever the family can pay toward a balance that day. This adapter is
 * used for the former only — see `apps/api` for where it is wired.
 *
 * `request.productId` selects the product; `request.amount` is validated
 * against what the checkout actually reports back rather than trusted, so a
 * product mispriced in the Chariow dashboard is caught before the buyer is
 * charged the wrong figure.
 *
 * Webhooks are "Pulses" in Chariow's vocabulary. Each Pulse carries an
 * `x-chariow-signature: sha256=<hex>` header — HMAC-SHA256 over the RAW body
 * bytes, keyed by that Pulse's own signing secret (`whsec_...`, generated by
 * Chariow, NOT the API key and not derived from it). The body is compact JSON
 * with escaped forward slashes, so it must never be re-serialised before
 * hashing.
 *
 * ⚠️ **UNVERIFIED AGAINST A LIVE ACCOUNT.** AGENTS.md forbids testing against
 * a real provider, so everything below is written from Chariow's published
 * developer documentation and is proven only by the port contract suite. Two
 * things must still be checked against a real delivery before this handles
 * real money:
 *
 *   1. `mapChariowStatus` — the exact status strings a real account returns.
 *      `unpaid` is checked before `paid` on purpose: it CONTAINS `paid`, and
 *      a naive substring match would credit an unpaid sale.
 *   2. The phone contract — LOCAL number, no leading zero, plus an ISO2
 *      country code, both required. An E.164 string alone is rejected.
 */

const BASE_URL = 'https://api.chariow.com/v1'

/**
 * Ordered, not a lookup table. `unpaid` contains `paid`, and testing success
 * before failure would credit a sale that was never paid — the exact bug the
 * integration reference calls out as having already cost a real credit.
 */
const STATUS_RULES: ReadonlyArray<{ pattern: RegExp; status: PaymentStatus }> = [
  { pattern: /unpaid/i, status: 'pending' },
  { pattern: /fail|error/i, status: 'failed' },
  { pattern: /cancel|abandon|refund/i, status: 'cancelled' },
  { pattern: /settle|complete|paid|success/i, status: 'succeeded' },
]

/** Minimal E.164 → {national, ISO2}. No library: none is in the lockfile, and
 * AGENTS.md requires asking before adding one. Covers CEMAC/UEMOA, where
 * Fineduc actually operates, plus enough neighbours to fail informatively
 * rather than silently elsewhere. */
const DIALLING_CODES: ReadonlyArray<readonly [string, string]> = [
  ['237', 'CM'],
  ['221', 'SN'],
  ['225', 'CI'],
  ['223', 'ML'],
  ['226', 'BF'],
  ['228', 'TG'],
  ['229', 'BJ'],
  ['241', 'GA'],
  ['242', 'CG'],
  ['243', 'CD'],
  ['235', 'TD'],
  ['236', 'CF'],
  ['227', 'NE'],
  ['33', 'FR'],
  ['1', 'US'],
]

export interface ChariowOptions {
  readonly apiKey: string
  /**
   * The Pulse SIGNING SECRET (`whsec_...`), read from
   * Automations → Pulses → your Pulse → Overview. Chariow generates it; it is
   * neither the API key nor derived from it, and using anything else here can
   * never produce a matching signature.
   */
  readonly webhookSecret: string
  readonly fetch: FetchLike
  readonly baseUrl?: string
  readonly policy?: HttpPolicy
}

export class ChariowProvider implements PaymentProvider {
  readonly name = 'chariow'
  readonly supportedMethods: readonly PaymentMethod[] = ['mobile_money', 'card']

  private readonly options: ChariowOptions
  private readonly baseUrl: string

  constructor(options: ChariowOptions) {
    if (!options.apiKey) {
      // Fail at construction, not at the first payment (ARCHITECTURE.md §9).
      throw new ProviderError('chariow', 'MISCONFIGURED', 'CHARIOW_API_KEY is required.')
    }
    this.options = options
    this.baseUrl = options.baseUrl ?? BASE_URL
  }

  async initiate(request: InitiatePaymentRequest): Promise<InitiatePaymentResult> {
    if (request.amount.amount <= 0n) {
      throw new ProviderError(this.name, 'INVALID_AMOUNT', 'Amount must be positive.')
    }
    if (!request.productId) {
      // Chariow has no field for an arbitrary amount — only a product to
      // sell. A caller that forgot to name one would otherwise get a 4xx
      // from Chariow with no clue what was missing.
      throw new ProviderError(this.name, 'PRODUCT_REQUIRED', 'Chariow charges a product price; productId is required.')
    }

    const { firstName, lastName } = splitPayerName(request.payerName)
    const phone = resolveChariowPhone(request.payerPhoneE164)

    const { status, body } = await postJson(
      `${this.baseUrl}/checkout`,
      {
        product_id: request.productId,
        email: request.payerEmail ?? placeholderEmail(request.payerPhoneE164),
        first_name: firstName,
        last_name: lastName,
        phone: { number: phone.national, country_code: phone.iso2 },
        redirect_url: request.returnUrl,
        custom_metadata: {
          reference: request.reference,
          idempotencyKey: request.idempotencyKey,
        },
      },
      { fetch: this.options.fetch, policy: this.options.policy, headers: this.authHeaders() },
    )

    const payload = asRecord(body)
    if (status >= 400) {
      throw new ProviderError(
        this.name,
        String(status),
        describeError(payload) ?? `Chariow rejected the request (HTTP ${status})`,
        status >= 500,
      )
    }

    const data = payload['data'] ? asRecord(payload['data']) : payload
    const purchase = asRecord(data['purchase'])
    const payment = asRecord(data['payment'])

    /*
     * `already_purchased` is a 200, not an error, and it is the failure mode
     * that matters for SUBSCRIPTION billing: Chariow blocks a repeat purchase
     * of a downloadable, course or bundle product while the customer holds an
     * active access grant. A school renewing its second month would land here
     * with `purchase: null` — which, left to the malformed-response branch
     * below, would read as "Chariow sent us nonsense" instead of naming the
     * one thing that is actually wrong: the product must be a LICENSE product
     * for a renewal to be possible at all.
     */
    if (data['step'] === 'already_purchased') {
      throw new ProviderError(
        this.name,
        'ALREADY_PURCHASED',
        typeof data['message'] === 'string' && data['message'].length > 0
          ? data['message']
          : 'Chariow refuses a repeat purchase of this product. A renewable subscription product must be of type "license"; downloadable, course and bundle products can only be bought once.',
      )
    }

    const saleId = purchase['id']
    const checkoutUrl = payment['checkout_url']
    if (typeof saleId !== 'string' || typeof checkoutUrl !== 'string') {
      throw new ProviderError(this.name, 'MALFORMED_RESPONSE', 'Chariow returned no purchase.id or payment.checkout_url.')
    }

    /*
     * The product's price is what Chariow will actually charge — not what
     * Fineduc believes it configured. A drift here means the Chariow
     * dashboard and the plan price have gone out of sync, and it is caught
     * NOW, before the buyer is sent to pay, rather than discovered from a
     * settled amount that does not reconcile.
     */
    const charged = readAmount(purchase['amount'])
    if (charged && !amountsRoughlyMatch(charged, request.amount)) {
      throw new ProviderError(
        this.name,
        'PRODUCT_PRICE_MISMATCH',
        `Chariow would charge ${charged.amount} ${charged.currency} for this product; expected ${request.amount.amount} ${request.amount.currency}. Check the product's price in the Chariow dashboard.`,
      )
    }

    return {
      providerRef: saleId,
      checkoutUrl,
      pushSent: false,
      // Never settled here. Only a re-pulled GET /sales/{id} settles money.
      status: 'pending',
    }
  }

  async getStatus(providerRef: string): Promise<ProviderPaymentStatus> {
    const { status, body } = await getJson(`${this.baseUrl}/sales/${encodeURIComponent(providerRef)}`, {
      fetch: this.options.fetch,
      policy: this.options.policy,
      headers: this.authHeaders(),
    })

    if (status >= 500) {
      throw new ProviderError(this.name, String(status), 'Chariow is unavailable.', true)
    }

    const payload = asRecord(body)
    const data = asRecord(payload['data'] ?? payload)
    return {
      providerRef,
      status: mapChariowStatus(data['status']),
      paidAmount: readAmount(data['amount']),
      failureReason: describeError(payload),
    }
  }

  /**
   * `x-chariow-signature: sha256=<hex>` — HMAC-SHA256 over the raw body bytes,
   * keyed by the Pulse signing secret.
   *
   * The RAW buffer is hashed, never a re-serialised object: Chariow transmits
   * compact JSON with escaped forward slashes and `\uXXXX` escapes, so
   * `JSON.stringify(parsed)` yields different bytes and every signature over a
   * payload containing a URL would fail.
   *
   * The `sha256=` prefix names the algorithm so the scheme can evolve. Anything
   * else is a scheme this adapter does not implement, and is refused rather
   * than compared — treating an unknown prefix as a bare digest would let a
   * future scheme downgrade to one we can forge.
   */
  verifyWebhook(rawBody: Buffer, headers: Record<string, string>): WebhookVerification {
    const provided = headers['x-chariow-signature'] ?? headers['X-Chariow-Signature']
    if (!provided) return { valid: false, reason: 'missing x-chariow-signature header' }
    if (!this.options.webhookSecret) return { valid: false, reason: 'CHARIOW_WEBHOOK_SECRET is not configured' }

    const received = provided.trim()
    if (!received.startsWith('sha256=')) {
      return { valid: false, reason: 'unsupported signature scheme' }
    }

    const expected = `sha256=${createHmac('sha256', this.options.webhookSecret).update(rawBody).digest('hex')}`

    const a = Buffer.from(expected)
    const b = Buffer.from(received)
    // Length-check first: timingSafeEqual throws on mismatched buffer sizes.
    if (a.length !== b.length) return { valid: false, reason: 'signature length mismatch' }
    return timingSafeEqual(a, b) ? { valid: true } : { valid: false, reason: 'signature mismatch' }
  }

  parseWebhook(payload: unknown): NormalizedPaymentEvent {
    const body = asRecord(payload)
    /*
     * A Pulse nests the sale under `sale`. `data` and the bare body are
     * accepted as fallbacks so a replayed delivery from an older shape, or a
     * hand-built fixture, still parses rather than throwing on money that has
     * genuinely moved.
     */
    const sale = asRecord(body['sale'] ?? body['data'] ?? body)
    const saleId = sale['id'] ?? sale['sale_id']
    if (typeof saleId !== 'string' || saleId.length === 0) {
      throw new ProviderError(this.name, 'MALFORMED_EVENT', 'sale.id is required.')
    }

    const eventName = typeof body['event'] === 'string' ? body['event'] : ''
    /*
     * Zero trust in this body for SETTLEMENT — the reconciliation path pulls
     * GET /sales/{id} before crediting anything ("never credit on the
     * webhook's word alone"). This method still has to return an honest
     * status, because it is what tells the queue whether to bother re-pulling
     * at all.
     */
    const status = mapChariowStatus(eventName, sale['status'])

    return {
      /*
       * `x-pulse-delivery-id` is Chariow's own idempotency key, but this port
       * hands `parseWebhook` the parsed body only — headers are not in scope.
       * Event name plus sale id is the stronger key for MONEY regardless: a
       * manual replay gets a fresh delivery id and would settle twice, while
       * this dedups it. Settlement is idempotent downstream either way.
       */
      eventId: `${eventName || 'chariow.unknown'}:${saleId}`,
      providerRef: saleId,
      reference: readReference(sale['custom_metadata']),
      status,
      paidAmount: readAmount(sale['amount']),
      occurredAt: parseTimestamp(
        sale['completed_at'] ?? sale['settled_at'] ?? sale['paid_at'] ?? sale['created_at'],
      ),
    }
  }

  async refund(providerRef: string, amount: Money, reason: string): Promise<RefundResult> {
    void providerRef
    void amount
    void reason
    // No refund endpoint in the integration reference — refunds are raised
    // from the Chariow dashboard. Throwing rather than reporting `failed`
    // says plainly that the action happens elsewhere, rather than reading as
    // "we tried and Chariow said no".
    throw new ProviderError(
      this.name,
      'REFUND_NOT_SUPPORTED',
      'Chariow refunds are raised from their dashboard, not through the API. Record the refund here once it is done.',
    )
  }

  private authHeaders(): Record<string, string> {
    return { authorization: `Bearer ${this.options.apiKey}`, accept: 'application/json' }
  }

}

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : {}
}

function mapChariowStatus(...candidates: unknown[]): PaymentStatus {
  for (const candidate of candidates) {
    if (typeof candidate !== 'string' || candidate.length === 0) continue
    const rule = STATUS_RULES.find((r) => r.pattern.test(candidate))
    if (rule) return rule.status
  }
  return 'pending'
}

/** Chariow requires both names; a single-word name gets `-` for the surname. */
function splitPayerName(payerName: string | undefined): { firstName: string; lastName: string } {
  const parts = (payerName ?? '').trim().split(/\s+/).filter(Boolean)
  if (parts.length === 0) return { firstName: 'Client', lastName: '-' }
  if (parts.length === 1) return { firstName: parts[0]!, lastName: '-' }
  return { firstName: parts[0]!, lastName: parts.slice(1).join(' ') }
}

function placeholderEmail(phoneE164: string): string {
  return `${phoneE164.replace(/[^\d]/g, '')}@no-email.fineduc.school`
}

interface ChariowPhone {
  readonly national: string
  readonly iso2: string
}

/**
 * E.164 → { national number, ISO2 }, the shape Chariow's checkout requires.
 * `+237670000001` → `{ national: "670000001", iso2: "CM" }`.
 *
 * No library — none is in the lockfile — so this covers the dialling codes
 * Fineduc actually operates in and throws for anything it does not
 * recognise, which fails loud rather than sending Chariow a payload it will
 * reject with a 400 that gives no hint why.
 */
function resolveChariowPhone(phoneE164: string): ChariowPhone {
  const digits = phoneE164.replace(/[^\d]/g, '')
  const match = [...DIALLING_CODES].sort((a, b) => b[0].length - a[0].length).find(([code]) => digits.startsWith(code))
  if (!match) {
    throw new ProviderError(
      'chariow',
      'UNSUPPORTED_PHONE_COUNTRY',
      `Could not determine a country for "${phoneE164}". Add its dialling code to resolveChariowPhone.`,
    )
  }
  const [code, iso2] = match
  const national = digits.slice(code.length)
  if (national.length === 0) {
    throw new ProviderError('chariow', 'INVALID_PHONE', `"${phoneE164}" has no digits after the country code.`)
  }
  return { national, iso2 }
}

/** Our reference, echoed back in custom_metadata. */
function readReference(metadata: unknown): string | undefined {
  const value = asRecord(metadata)['reference']
  return typeof value === 'string' && value.length > 0 ? value : undefined
}

/** `{ value, currency }`, major units — Chariow shops can be XOF, USD or EUR. */
function readAmount(amount: unknown): Money | undefined {
  const record = asRecord(amount)
  const value = record['value']
  const currency = record['currency']
  if (value == null || typeof currency !== 'string') return undefined
  try {
    return Money.ofMajor(String(value), currency as CurrencyCode)
  } catch {
    return undefined
  }
}

/**
 * Whether Chariow's product price and Fineduc's expected price agree, to a
 * currency's own smallest unit — never blocking on a currency LABEL
 * mismatch alone, only on the number, matching the integration reference's
 * own anti-fraud rule (compare on amount, not on how the currency is tagged).
 */
function amountsRoughlyMatch(charged: Money, expected: Money): boolean {
  if (charged.currency !== expected.currency) return false
  const tolerance = 10n ** BigInt(exponentOf(charged.currency)) // one whole unit
  const diff = charged.amount > expected.amount ? charged.amount - expected.amount : expected.amount - charged.amount
  return diff <= tolerance
}

function describeError(payload: Record<string, unknown>): string | undefined {
  const message = payload['message']
  if (typeof message === 'string' && message.length > 0) return message
  const errors = asRecord(payload['errors'])
  const first = Object.values(errors)[0]
  const text = Array.isArray(first) ? first[0] : first
  return typeof text === 'string' ? text : undefined
}

function parseTimestamp(value: unknown): Date {
  if (typeof value !== 'string') return new Date()
  const parsed = new Date(value)
  return Number.isNaN(parsed.getTime()) ? new Date() : parsed
}
